plugin:
  id: ptm-remap
  name: PTM Position Remapping
  version: 1.0.0
  description: Remap PTM positions from peptides to protein sequences using UniProt data
  author: Cauldron Team
  category: utilities
  icon: swap_horiz
  repository: https://github.com/noatgnu/ptm-remap-plugin

runtime:
  environments: ["python"]
  entrypoint: remap_ptm.py

inputs:
  - name: input_file
    label: Input File
    type: file
    required: true
    description: Tab-separated or CSV file containing peptide data
    file_types:
      - .txt
      - .tsv
      - .csv

  - name: peptide_column
    label: Peptide Sequence Column
    type: column
    required: true
    description: Column containing peptide sequences
    source: input_file

  - name: position_in_peptide_column
    label: Position in Peptide Column
    type: column
    required: true
    description: Column containing the position of the PTM within the peptide
    source: input_file

  - name: uniprot_acc_column
    label: UniProt Accession Column
    type: column
    required: true
    description: Column containing UniProt accession IDs
    source: input_file

  - name: fasta_file
    label: FASTA File (Optional)
    type: file
    required: false
    description: Optional FASTA file with protein sequences. If not provided, sequences will be fetched from UniProt.
    file_types:
      - .fasta
      - .fa

execution:
  argsMapping:
    input_file: "--input"
    peptide_column: "--peptide-col"
    position_in_peptide_column: "--position-col"
    uniprot_acc_column: "--uniprot-col"
    fasta_file: "--fasta"
  outputDir: "--output-dir"
  requirements:
    python: ">=3.10"
    pythonRequirementsFile: requirements.txt

outputs:
  - name: remapped_peptides.txt
    path: remapped_peptides.txt
    type: data
    description: Tab-separated file with remapped PTM positions
